# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "chartedart"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a table in a single query. The limit clause will be
# ignored if it exceeds this value.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version_num;` on the remote database to check.
major_version = 17

[db.pooler]
enabled = false
# Port to use for the pooler URL.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"
# The maximum length in bytes of HTTP request headers. (default: 4096)
# max_header_length = 4096

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1"
# OpenAI API Key to use for Supabase AI.
openai_api_key = "env(OPENAI_API_KEY)"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://127.0.0.1:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending a confirmation OTP via SMS.
# Variables: .Code (6-digit typing code)
template = "Your code is {{ .Code }}"

# Use pre-defined map of phone number to OTP for testing.
# [auth.sms.test_otp]
# 4152127777 = "123456"

# Configure one of the supported SMS providers: `twilio`, `twilio_verify`, `messagebird`, `textlocal`, `vonage`.
# [auth.sms.twilio]
# account_sid = "env(SUPABASE_AUTH_SMS_TWILIO_ACCOUNT_SID)"
# message_service_sid = "env(SUPABASE_AUTH_SMS_TWILIO_MESSAGE_SERVICE_SID)"
# auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

[auth.external.apple]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_APPLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_APPLE_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_APPLE_URL)"

[auth.external.azure]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_AZURE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_AZURE_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_AZURE_URL)"

[auth.external.bitbucket]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_BITBUCKET_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_BITBUCKET_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_BITBUCKET_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_BITBUCKET_URL)"

[auth.external.discord]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_URL)"

[auth.external.facebook]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_FACEBOOK_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_FACEBOOK_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_FACEBOOK_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_FACEBOOK_URL)"

[auth.external.github]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_GITHUB_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_GITHUB_URL)"

[auth.external.gitlab]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GITLAB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GITLAB_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_GITLAB_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_GITLAB_URL)"

[auth.external.google]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_URL)"

[auth.external.keycloak]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_KEYCLOAK_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_KEYCLOAK_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_KEYCLOAK_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_KEYCLOAK_URL)"

[auth.external.linkedin]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_LINKEDIN_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_LINKEDIN_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_LINKEDIN_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC  providers.
url = "env(SUPABASE_AUTH_EXTERNAL_LINKEDIN_URL)"

[auth.external.notion]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_NOTION_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_NOTION_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_NOTION_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_NOTION_URL)"

[auth.external.twitch]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_TWITCH_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_TWITCH_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_TWITCH_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_TWITCH_URL)"

[auth.external.twitter]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_TWITTER_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_TWITTER_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_TWITTER_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_TWITTER_URL)"

[auth.external.slack]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_SLACK_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_SLACK_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_SLACK_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_SLACK_URL)"

[auth.external.spotify]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_SPOTIFY_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_SPOTIFY_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_SPOTIFY_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_SPOTIFY_URL)"

[auth.external.workos]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_WORKOS_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_WORKOS_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_WORKOS_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_WORKOS_URL)"

[auth.external.zoom]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_ZOOM_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_ZOOM_SECRET)"
# Overrides the default auth redirectURL, defaults to the first URL in additional_redirect_urls
redirect_uri = "env(SUPABASE_AUTH_EXTERNAL_ZOOM_REDIRECT_URI)"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure AD,
# or any other third-party OIDC providers.
url = "env(SUPABASE_AUTH_EXTERNAL_ZOOM_URL)"

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"

[functions]
# Import map for Deno runtime, used to configure package versions and
# aliases.
# import_map = "./functions/import_map.json"

[edge_runtime]
policy = "oneshot"
# Enter an IP address, hostname, or CIDR for the edge runtime to connect to.
inspector_port = 8083
